# Generated by Django 5.2.17 on 2026-09-12 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Category name (e.g., Baby Wear)', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of this category')),
                ('image', models.ImageField(blank=True, help_text='Category showcase image', null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle category visibility on the site')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Product title (e.g. Baby Full Sleeve T-Shirt)', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('product_code', models.CharField(db_index=True, help_text='Unique SKU or factory product code (e.g., NR-BW-001)', max_length=50, unique=True)),
                ('material', models.CharField(blank=True, help_text='Fabric or material composition (e.g., 100% Combed Cotton Interlock)', max_length=150)),
                ('short_description', models.CharField(blank=True, help_text='Concise summary for cards and search previews', max_length=300)),
                ('description', models.TextField(help_text='Full manufacturing specifications, features, and details')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight on homepage featured section')),
                ('is_published', models.BooleanField(default=True, help_text='Publish product to catalogue')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Sort order priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Product category', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(help_text='Product photograph', upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive alt text for accessibility and SEO', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as main thumbnail/cover image')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in gallery')),
                ('product', models.ForeignKey(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Color name (e.g., Pastel Sky Blue)', max_length=50)),
                ('hex_code', models.CharField(default='#000000', help_text='Hexadecimal color code (e.g., #87CEEB)', max_length=7)),
                ('image', models.ImageField(blank=True, help_text='Optional photo of the product specifically in this color', null=True, upload_to='products/colors/')),
                ('product', models.ForeignKey(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
                'unique_together': {('product', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_name', models.CharField(help_text='Size label (e.g., 0-3 Months, Free Size)', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in size selector')),
                ('product', models.ForeignKey(help_text='Associated product', on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'ordering': ['display_order', 'size_name'],
                'unique_together': {('product', 'size_name')},
            },
        ),
    ]
