# Generated by Django 5.2.17 on 2026-09-12 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryProcessStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_number', models.PositiveIntegerField(default=1, help_text='Sequential step number (1, 2, 3...)')),
                ('title', models.CharField(help_text='Step title (e.g., Fabric Knitting & Inspection)', max_length=150)),
                ('description', models.TextField(help_text='Detailed explanation of this production phase')),
                ('image', models.ImageField(blank=True, help_text='Photograph of this activity', null=True, upload_to='factory/steps/')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle step visibility in the timeline')),
            ],
            options={
                'verbose_name': 'Factory Process Step',
                'verbose_name_plural': 'Factory Process Steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='FactorySection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_key', models.CharField(help_text='Internal key (e.g., overview, machinery, quality_control)', max_length=50, unique=True)),
                ('title', models.CharField(help_text='Section heading', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Supporting sub-heading', max_length=250)),
                ('content', models.TextField(help_text='Detailed narrative')),
                ('image', models.ImageField(blank=True, help_text='Section showcase image', null=True, upload_to='factory/sections/')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display priority')),
            ],
            options={
                'verbose_name': 'Factory Section',
                'verbose_name_plural': 'Factory Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('factory', 'Factory & Facility'), ('production', 'Production Activities'), ('machinery', 'Machinery & Equipment'), ('products', 'Product Showcase'), ('showroom', 'Showroom'), ('packaging', 'Finishing & Packaging')], default='factory', max_length=30)),
                ('title', models.CharField(help_text='Photo caption / title', max_length=150)),
                ('caption', models.CharField(blank=True, help_text='Short narrative or subtitle', max_length=255)),
                ('image', models.ImageField(help_text='High-resolution photograph', upload_to='gallery/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gallery Item',
                'verbose_name_plural': 'Gallery Items',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Showroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Showroom title (e.g., Main Factory Showroom)', max_length=150)),
                ('description', models.TextField(help_text='Showroom introduction and visiting guidelines')),
                ('address_override', models.TextField(blank=True, help_text='Optional specific address if distinct from factory')),
                ('image', models.ImageField(blank=True, help_text='Primary showroom photograph', null=True, upload_to='showroom/')),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Showroom',
                'verbose_name_plural': 'Showrooms',
                'ordering': ['display_order'],
            },
        ),
    ]
