# Generated by Django 5.2.17 on 2026-09-12 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text='Buyer / Contact Name', max_length=120)),
                ('email', models.EmailField(blank=True, help_text='Email address', max_length=254)),
                ('phone', models.CharField(help_text='Contact / WhatsApp phone number', max_length=50)),
                ('subject', models.CharField(help_text='Inquiry subject', max_length=200)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('wholesale', 'Wholesale / Bulk Order'), ('manufacturing', 'Custom Manufacturing / Contract'), ('product', 'Specific Product Inquiry')], default='general', max_length=20)),
                ('product_of_interest', models.CharField(blank=True, help_text='Product name or SKU if inquiry originates from a product page', max_length=200)),
                ('message', models.TextField(help_text='Inquiry message, quantity requirements, or notes')),
                ('is_read', models.BooleanField(default=False, help_text='Mark whether admin has reviewed this inquiry')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact & Wholesale Inquiry',
                'verbose_name_plural': 'Contact & Wholesale Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
