# Generated by Django 5.2.17 on 2026-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='New Rahad Hosiery & Garments', help_text='Official business name', max_length=150)),
                ('tagline', models.CharField(default='Quality Hosiery & Baby Wear — Manufactured With Care', help_text='Hero tagline / brand promise', max_length=250)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon', null=True, upload_to='branding/')),
                ('phone_primary', models.CharField(blank=True, default='+880 1XXX-XXXXXX', help_text='Primary phone', max_length=50)),
                ('phone_secondary', models.CharField(blank=True, help_text='Secondary phone / landline', max_length=50)),
                ('whatsapp_number', models.CharField(blank=True, default='+880 1XXX-XXXXXX', help_text='WhatsApp inquiry number (international format without spaces/dashes, e.g., 8801700000000)', max_length=50)),
                ('email_primary', models.EmailField(blank=True, default='info@newrahad.com', help_text='Primary contact email', max_length=254)),
                ('email_inquiry', models.EmailField(blank=True, default='sales@newrahad.com', help_text='Sales / wholesale inquiry email', max_length=254)),
                ('physical_address', models.TextField(blank=True, default='Factory & Showroom Location, Bangladesh', help_text='Full physical street and factory address')),
                ('google_maps_embed_url', models.TextField(blank=True, help_text='Google Maps iframe embed src URL')),
                ('google_maps_page_url', models.URLField(blank=True, help_text='Direct link to open location in Google Maps app/website')),
                ('facebook_url', models.URLField(blank=True, help_text='Official Facebook Page URL')),
                ('meta_title_default', models.CharField(default='New Rahad Hosiery & Garments | Manufacturer of Hosiery & Baby Wear', help_text='Default browser title for SEO', max_length=150)),
                ('meta_description_default', models.TextField(blank=True, default='New Rahad Hosiery & Garments is a genuine manufacturer of premium hosiery and baby wear products. Explore our in-house factory production and product catalogue.', help_text='Default search engine snippet')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
